<?php

$texts = array(

//"dot"=>"・",
"dotSlash"=>" / ",
//","=>"、",
//"asterist"=>"※",
"("=>" (",
")"=>") ",
//"["=>"【",
//"]"=>"】",
"leftBracket"=>' "',
"rightBracket"=>'" ',

//"man"=>"万",
//"yen"=>"円",
//"includingTax"=>"税込",
"productCountUnit"=>"items",
//"mei"=>"名",

//"year"=>"年",
//"month"=>"月",

"sun"=>"Sun",
"mon"=>"Mon",
"tue"=>"Tue",
"wed"=>"Wed",
"thu"=>"Thu",
"fri"=>"Fri",
"sat"=>"Sat",

"mon."=>"Mon.",
"fri."=>"Fri.",
//"sat"=>"土",

//"sun."=>"日曜",
"sat."=>"Sat.",

"friday"=>"Fri.",

"all"=>"All",

//"holiday"=>"祝祭日",
"sunHoliday"=>"Sun. & National Holidays",

"shuheiNakata"=>"Shuhei Nakata",

"back"=>"Back",
"toPrev"=>"Prev.",
"toNext"=>"Next",

//"check-"=>"を見る",

"required"=>"Required",

//////////////////////////////////////////////////////////////////////////////////////////

//"notFound"=>"見つかりませんでした",
//"pageNotFound"=>"ページが見つかりませんでした",

//////////////////////////////////////////////////////////////////////////////////////////

//"nakatahanger"=>"NAKATA HANGER",

"aHomeForYourClothes"=>"A Home for Your Clothes",
//"aHomeForYourClothes2"=>"A Home for Your Clothes",
"aHomeForYourClothesMessage"=>"Just as people have a place to come home to,<br>clothes need a place to  call home, too.<br>Your clothes are important to you. <br device='sp'>Our warm welcome awaits them.",

"products"=>"Products",
//"products2"=>"Products",
"gift"=>"Gifts",
"showroom"=>"Showroom",
//"showroom2"=>"Showroom",
"stores"=>"Stores",
//"howToChoose"=>"ハンガーの選び方",
//"howToChoose2"=>"How to choose",

//"home"=>"ホーム",
"backToHome"=>"Home",
"myPage"=>"My Account",
//"companyInfo"=>"会社概要",
//"search"=>"検索",
"webGuide"=>"Help",
"faq"=>"FAQ",
//"faqen"=>"海外販売について",
//"spelling"=>"ネーム入れFAQ",
"inquiry"=>"Inquiry",
"privacyPolicy"=>"Privacy Policy",
"shippingPolicy"=>"Shipping Policy",
"refundPolicy"=>"Refund Policy",
"legal"=>"Legal Notice",
"japanese"=>"JAPANESE",
//"english"=>"ENGLISH",
//"blog"=>"ブログ",
//"blog2"=>"Blog",

"men2"=>"For Men",
"women2"=>"For Women",
"forMen"=>"For men",
"forWomen"=>"For women",
"productListForMen"=>"All Hangers for Men",
"productListForWomen"=>"All Hangers for Women",
"jacketHanger"=>"Suit & Jacket Hangers",
"shirtHanger"=>"Shirt Hangers",
"bottomHanger"=>"Trouser & Pants Hangers",
"necktieBeltHanger"=>"Tie & Belt Hangers",
"stoleBeltHanger"=>"Scarf & Belt Hangers",
"others"=>"Others",
"clothBrush"=>"Clothes Brushes",
"shoehorn"=>"Shoe Horns",
"hangerRack"=>"Coat Rack",
"stand"=>"Valet Stand",
"kimonoHanger"=>"Kimono Hangers",
"kidsHanger"=>"Kids Hangers",
"petHanger"=>"Pet Clothes Hangers",
"otherAccessories"=>"Accessories",
"outletHanger"=>"Outlet",
"series"=>"Series",
"bySeries"=>"Series",
//"nhSeries"=>"NH",
//"autSeries"=>"Authentic",
//"setSeries"=>"SET",
//"option"=>"オプション",
//"nameEngraving"=>"ネーム入れ",

//"jacket2"=>"Jacket",
//"shirt2"=>"Shirt",
//"bottom2"=>"Bottom",
//"others2"=>"Others",

//"gift2"=>"Gift",
"productListForGift"=>"Gift",
//"giftForMen"=>"男性に贈る",
//"giftForWomen"=>"女性に贈る",
//"giftForBoth"=>"男女ペアで贈る",
//"weddingGift"=>"引出物",
//"familyCelebration"=>"内祝い",
//"bridal"=>"ブライダル",
//"movingToSpecialSite"=>"特設サイトに移動します",
//"graduationGift"=>"卒業記念品",
//"schoolYear"=>"年度",
//"gradGift"=>"卒業記念",
//"forOrg"=>"記念品・ノベルティ",
//"consideringOrgGift"=>"法人記念品用にご検討されている企業様",
//"giftDesc1"=>"使ってみて本当に良いものは、大切な人にも贈りたい。",
//"giftDesc2"=>"上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。",

//"aboutNameEngraving"=>"ネーム入れについて",
//"nameEngraving2"=>"Name Engraving",

"news"=>"News",
//"news2"=>"News",
"media"=>"Media Appearance",
"journal"=>"Journal",
"backToNewsList"=>"Back to news list",

"about"=>"About NAKATA HANGER",
//"about2"=>"About",
//"concept2"=>"Concept",
"conceptMainText"=>"Just as people have a place to come home to,<br>clothes need a place to call home, too.<br>Your clothes are important to you. Our warm welcome awaits them.",
//"conceptMainText"=>"<div><span>人に帰る家があるように</span><span>洋服にも帰る場所があります。</span></div><div><span>季節の移ろいとともに</span><span>心を踊らせてくれる大切な洋服。</span></div><div><span>木のぬくもりを感じながら</span><span>次の出番をここで待っています。</span></div>",
"conceptSubText"=>"<p>NAKATA KOGEI Co., Ltd. is the only maker specializing in wooden hangers in Japan that has continued to meet the extremely high demands of Japanese apparel companies in the constantly changing and growing fashion culture since the company's foundation in 1946. NAKATA HANGER is a wooden hanger made in Japan that NAKATA KOGEI has carefully re-examined the hanger from the user's point of view and made the best use of the skills, knowledge, and experiences accumulated over many years. Each hanger is made by craftsmen, and the hanger has a sophisticated design and a function to keep clothes in good shape. Our hangers have a universality that does not change over time.</p><p>NAKATA HANGER is also widely used as a gift. It is popular as a gift for someone important to you, as a wedding gift, and as a graduation souvenir. We have a concept of \"Hanging clothes is happiness\".  (The words \"clothes\" and \"happiness\" are a pun in Japanese.) The craftsmen handcraft each hanger one by one with the hope that the giver and the user will be happy. We continue to pursue the potential of hangers and propose a lifestyle through wooden hangers.</p>",
"brandHistory"=>"The History of NAKATA HANGER",
//"brandHistory2"=>"Brand History",
"craftsmanship"=>"Craftsmanship",
//"craftsmanship2"=>"Craftsmanship",
"craftsmanshipTitle"=>"Making the best hangers",
"craftsmanshipMainText"=>"We have many kinds of skills and commitments.</p><p>The first one is, of course, the commitment to the hanger product. We always think about what's best for the clothes and the customers who use them. We are always in pursuit of the woodworking skills that create the shape of hangers and painting skills that give more expressions to our products.</p><p>The second one is the commitment to wooden products. Just as each human has a personality, each tree has its own characteristics. Our craftsmen check the hardness, texture, and wood grains of each piece of wood to make hangers with a natural finish.",
"craftsmanshipSubTitle"=>"Commitment to materials",
"craftsmanshipSubText"=>"NAKATA HANGER's products mainly use beech wood from Europe. Beech has been used to make hangers for a long time because it has moderate hardness and stability.<br>Technically, hangers can be made from other woods, but conifers with a lot of resin and warp may damage clothes and fabrics. Even hardwoods that are too heavy or too strong will spoil ease of use and beauty. Beech is the most suitable wood for hangers because it has a smooth finish when polished carefully.",
"forEnvironment"=>"Environment",
"sustanableEnronment"=>"For a sustainable environment",
"enronmentMainText"=>"In order to maintain forests, we purchase wood that is managed under the rules of planned planting and logging rather than unplanned logging.<br>Planned logging allows sunlight to shine into the forest, plants to grow in the lower layers, and more organisms to inhabit there. It also allows the trunk to grow thicker that makes the forest resistant to wind and snow, improves the water source recharge function, and prevents sediment disaster.<br>By establishing this life cycle, the environment of the forest is maintained. We believe that a sustainable environment and society are important for the future of the next generation.",
"production"=>"Product making",
"environmentSubText1"=>"We use the edge materials of hangers to make small hangers, the edge materials of small hangers to make pants hangers, and the edge materials of pants hangers to make craft products. In this way, we make effective use of natural resources without wasting them.",
"energyUse"=>"Energy use",
"environmentSubText2"=>"The scraps that are too small to be made into products are also important resources for us. The scraps and sawdust are burned in an incinerator and steam are generated in a boiler to be used for the process of bending wood, drying hangers, and heating the factory.",
"moreUse"=>"Further use",
"environmentSubText3"=>"We even use the ashes left in the incinerator. Ashes from broad-leaved trees are used to remove the scum in making \"Tochi mochi\" (Japanese horse chestnut cake), a specialty of the Tajima region where our head office is located in Hyogo prefecture. We provide the ashes made by burning the scraps and sawdust for the production of local specialties.",
"companyInfo"=>"Company",
//"company2"=>"Company",
//"message2"=>"Message",
//"presidentMessageTitle"=>"世界一満足していただけるハンガーを届けたい。",
//"presidentMessage"=>"中田工芸は1946年、創業者である中田敏雄と木製ハンガー職人との出会いからその歴史が始まりました。以後、戦後の復興、高度成長時代を通じて、店舗などの業務用ハンガーを主としてファッション業界に貢献してまいりました。その過程でなによりも大切にしてきたのは顧客からの信頼を守ることです。品質を重視し、別注デザインに対応する技術、納期を遵守する生産管理の構築でした。こうした企業文化は、自社ブランド「NAKATA HANGER」の展開へも引き継がれ、一般のお客様からも評価をいただくようになりました。</p><p>私は長年にわたり日本で作り続けてきた自社の製品には世の中に知られていない可能性があると感じましたので、少しでも多くの人にその価値を伝えたいと思い、試行錯誤を繰り返してきました。その結果分かったことは、我が社のハンガーが持っている可能性は自分の想像を遥かに超えていたということです。ハンガーというもの（製品）を通じて、多くの感動や人との出会いに恵まれていることに驚くと共に、感謝の念に堪えません。</p><p>中田工芸の経営理念は「挑戦し、成長する」。ハンガーを通して、まだ見ぬ出会いや出来事に期待を膨らませていますが、そのためには常に新しいことにチャレンジし続けてこそです。100年企業へ向けて、これからも挑戦を続け、社会のお役に立てるように努力を重ねて参ります。",
//"president"=>"代表取締役社長",
"companyName"=>"Company Name",
"nakatakogeiCompany"=>"NAKATA KOGEI Co., Ltd.",
"foundation"=>"Foundation",
//"showa"=>"昭和",
//"heisei"=>"平成",
"businessDesc"=>"Business",
"presidentPerson"=>"President",
"location"=>"Location",
//"capital"=>"資本金",
//"employee"=>"従業員",
//"mainBank"=>"主要取引銀行",
"companyHistory"=>"Company History",
//"companyHistory2"=>"Company History",

//"orderFlow"=>"ご注文の流れ",
"aboutShippingFee"=>"Shipping Fee",
//"aboutPaymentMethod"=>"支払い方法について",
//"aboutShoppingPoint"=>"ショッピングポイントについて",
//"aboutWrappingPackage"=>"ラッピング・梱包について",
//"aboutNoshi"=>"のしについて",
//"aboutReceiptDetails"=>"領収書・明細書について",
"aboutHangerSize"=>"About Hanger Size",

//"viewAll"=>"View all",
//"readMore"=>"Read more",
//"productDetails"=>"Product details",

"feature"=>"Feature",
//"feature2"=>"Feature",

//"series2"=>"series",
//"ranking2"=>"Ranking",
//"customer2"=>"Customer",
//"information2"=>"Information",
//"others2"=>"Others",
//"access2"=>"access",
//"map2"=>"map",
//"open2"=>"open",
//"close2"=>"close",

"sortBy"=>"Sort by",
"lineupOrder"=>"Product Line-up",
"ascPriceOrder"=>"Price (Low to High)",
"descPriceOrder"=>"Price (High to Low)",

"sizeSelectable"=>"SIZE SELECTABLE",

"soldOut"=>"Temporarily Sold Out",

"seriesDescNh"=>'NH series is the highest grade hangers made by craftsmen from a single plate of special thickness without any joints. The common design is a "trench" that gives the collar an elegant look. They are the ultimate hangers made by hand by craftsmen.',
"seriesDescAut"=>"AUTHENTIC is a highly convenient series that can be selected according to a wide range of purposes. It has been used by various apparel brands, and the hangers have functional features designed with attention to detail and quality.",
"seriesDescSet"=>"SET series is a reasonably priced model that maintains a high level of quality. It is a set of 5 pieces with basic functions for stylish and casually enjoying fashion.",

"seriesDescNh1"=>"<span>NH collection hanger is made from a single, thick plank of beechwood.</span><span>Our skilled craftsman carves the board by freehand to make a hanger.</span>",
"seriesDescNh2"=>"Why do we need a thick plank for NH collection?  It's because to whittle a deep curve line.<br>The clothes are cut to fit the human body. So it's best to keep the person wearing when storing.<br>To make the natural round line from neck to back, whittling a board is the most effective way.<br><br>Smooth roundness created by hands.<br>Our hanger is made from natural beech. We use only beech grown in Europe and intentionally cultivated.<br>Natural wood has each wood grain and fiber direction. It's different from one by one.<br>Our craftsmen make sure of each wooden character and carve out the wood.",
"seriesDescAut1"=>"<span>The hangers of Authentic series have functional features designed with attention to detail and quality.</span><span>They have been used by various apparel brands.</span>",
"seriesDescAut2"=>"Highly convenient for a broad range of purposes, these hangers have been used by many high-end apparel brands.<br>These designs are distinguished by their functional features, and the pieces are crafted with great attention to detail and quality.",
"seriesDescSet1"=>"<span>SET series is a reasonably priced model that maintains a high level of quality.</span><span>It is a set of 5 pieces with basic functions for stylish and casually enjoying fashion.</span>",
"seriesDescSet2"=>"",

"registerMailMagazine"=>"Join the club.",
"sendingNewProductsAndCampaign"=>"Get insider access to new promotions and promo code.",
"emailAddress"=>"Email",
"subscription"=>"Subscribe",

"videoHasSound"=>"This video has sound.",

//////////////////////////////////////////////////////////////////////////////////////////

//"categoryMen"=>"男性用のキャッチコピー ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯◯",
//"categoryMenJacket"=>"男性用ジャケットのキャッチコピー ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯ ◯◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯◯ ",
//"categoryOthersKids"=>"子供の服も、できれば気持ちよくすっきりと収納したい。<br>それも毎日のことだから、分かりやすく探しやすく。<br>子どもにとっても日々の習慣になったら嬉しいな・・・<br><br>親も子どもも愉しめるハンガーを揃えました。",
//"categoryGift"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",
//"categoryGiftMen"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",
//"categoryGiftWomen"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",
//"categoryGiftPair"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",

//////////////////////////////////////////////////////////////////////////////////////////

"country"=>"Country",
"japan"=>"Japan",

//"zipMark"=>"〒",
"tel"=>"Phone",
//"fax"=>"Fax",

//"prefecture"=>"都道府県",
//"city"=>"都市",
"address"=>"Address",
//"telNum"=>"電話番号",
"businessHours"=>"Hours",

"contact"=>"Contact",
"region"=>"Region",

"headquarters"=>"Head Office",
"hqAddr"=>"92 Ebara, Hidaka-cho, Toyooka-shi, Hyogo, ",

"byCar"=>"By car",
"byTrain"=>"By train",
"wayToHqByCar"=>"5 minutes from Hidaka Kannabe Kogen IC exit on Kitakinki-Toyooka Expressway",
"wayToHqByTrain"=>"1-minute walk from Ebara Station on JR Sanin Line",

"aoyama"=>"Aoyama",
"aoyamaShowroom"=>"Aoyama Showroom",
//"srZip"=>"107-0062",
"srAddr"=>"1-1-1 Minami-aoyama, Minato-ku, Tokyo",
"srBuilding"=>"Shin-Aoyama Bldg. (Aoyama Twin) West 1F",
"visitingReservation"=>"Make an appointment",

"nearestStation"=>"Nearest station",
"aoyamaIcchome"=>"Aoyama-itchome",
"station"=>" Station",
"3-4exit"=>"Exit 3, 4",
"tokyoMetro"=>"Tokyo Metro",
"ginzaLine"=>"Ginza Line",
"hanzomonLine"=>"Hanzomon Line",
"toeiSlashOedoLine"=>"Toei Oedo Line",
"dutyfree"=>"* Tax-free service available",

//"woodenHanger"=>"木製ハンガー",
//"displayAccessories"=>"ディスプレイ什器",
//"interior"=>"インテリア",
//"productionOfWoodenCrafts"=>"木製クラフトの製造及び販売",

//"tajimaBank"=>"但馬銀行",
//"tajimaShinkinBank"=>"但馬信用金庫",
//"smbc"=>"三井住友銀行",

"name"=>"Name",
"inquiryContents"=>"Comments",
"enterText"=>"Enter",
"enterForConfirmation"=>"Re-enter for confirmation",
"confirmInquiry"=>"Submit the inquiry",
"pleaseEnter"=>"This text is required.",
"enterPhoneFormat"=>"Enter in the phone number format.",
"enterEmailFormat"=>"Enter in the email address format.",
"emailsNotMatched"=>"The email addresses don't match.",
"okToSendFollowing"=>"Please check the texts before submitting.",
"send"=>"Submit",

"inquiryThankYou"=>"Thank you for your inquiry.",
"inquiryThankYouTexts"=>"Thank you for contacting NAKATA HANGER.&nbsp; We will contact you by email.<br><br>Please add our email address (".EMAIL_INQUIRY.") to your address list to avoid storing our emails in your spam folder.",
"inquiryFailed"=>"Failed to submit the inquiry form.",
"inquiryFailedTexts"=>"We apologize for the inconvenience, but could not submit the form successfully.<br>Please call us with the following phone number.",
"inquiryTel"=>"Phone Number",

"thankYouInquiry"=>"Thank you for your inquiry.",

"showMore"=>"Show more",
"backToList"=>"Back to list",
"instagramDesc"=>"This page introduces Instagram posts with the hastag #NAKATAHANGER.<br>Our staff may contact you to show your posts in this page.",
"inquiryAboutContents"=>"Inquiry about this content",
"inquiryAboutInstagramContents"=>"Inquiry about the Instagram content",
"inquiryInstagramDesc"=>"For inquiries about Instagram content (such as requesting to stop posting your own content), please use the form below.",
"instagramContent"=>"Instagram content",

//////////////////////////////////////////////////////////////////////////////////////////

"showroomDesc"=>"Visit our showroom in Aoyama, Tokyo to touch and feel the forms, textures, and colors of our hangers.<br>You can bring your suit and jackets and hang them on our hangers.<br>We help you to find the best hangers for your clothes.",

//"officialOnlineShop"=>"直営オンラインショップ",
//"nhcomDesc"=>"兵庫・豊岡の自社工場で製造した NAKATA HANGER ですべての商品を販売しています。<br>ハンガーへの名入れやギフトラッピングも承ります。",

//"exclusiveService"=>"限定特典",
//"nhcomSpecial1"=>"ご注文金額 ".number_format(tax(FREE_SHIPPING_PRICE_WITHOUT_TAX))." 円（税込）以上で送料無料",
//"nhcomSpecial2"=>"ご注文金額 100 円ごとに 1 ポイント",
//"nhcomSpecial3"=>"初回購入時に 300 ポイントをプレゼント",
//"nhcomSpecial4"=>"WEB 限定商品「<a href='".getHref("set")."' nh-link-color>SET シリーズ</a>」",

"dealingStores"=>"Stores",
"dealingStoresDesc"=>"The products of NAKATA HANGER are available at the following stores. <br device='pc'>The product line-up differs depending on the store. <br device='pc'>Please contact each store for inquiries about the available hangers.",
"productionDelay"=>"",

//////////////////////////////////////////////////////////////////////////////////////////

"metaKeywordsCommon"=>"NAKATA HANGER,NAKATAHANGER,NAKATA KOGEI,wooden hanger,woodenhanger",

"metaDescTop"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
//"metaDescEnglish"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",

//"metaDescStores"=>"Information about NAKATA HANGER's Aoyama Showroom in Tokyo. Feel the forms, textures, and colors of the wooden hangers.",
//"metaDescNews"=>"商品、イベントやメディア掲載などの NAKATA HANGER の最新ニュースをお知らせします。",
//"metaDescHowTo"=>"最適な木製ハンガーを選ぶためのポイント。スーツやジャケット、シャツ、ボトム等の洋服に合う肩幅のサイズや使い方、収納や保管のコツをお伝えします。",
//"metaDescGraduation"=>"ナカタハンガーの卒業記念品。「福（服）をかける」縁起物として木製ハンガーを多くの小中学校や高校の卒業生にお使い頂いています。",
//"metaDescNovelty"=>'法人企業や店舗の創立周年記念やオープン祝いの、贈り物やノベルティに。名入れ（ネーム入れ）やロゴ入れで、オリジナル木製ハンガーを承ります。大切な記念に"ふくをかける"ハンガーを。',
//"metaDescPrivacyPolicy"=>"ナカタハンガーのプライバシーポリシー「個人情報」についてご案内。",
//"metaDescLegal"=>"ナカタハンガーの公式通販サイトの特定商取引法に基づく表記ページ。",

//"metaDescAbout"=>"The concept and history of the brand NAKATA HANGER. The wooden hangers are made one by one in Japan by the craftsmen. We propose a lifestyle with hangers as household and gift items.",
//"metaDescCraftsmanship"=>"Our commitment to produce the best wooden hangers. About the craftsman's skills, beech wood, and the efforts for the sustainable environment.",
//"metaDescCompany"=>"「世界一満足していただけるハンガーを届けたい。」との想いのもと、国内のみならず海外販売を行っています。会社概要、社長メッセージ、ビジョン、企業理念をお伝えします。",
//"metaDescHistory"=>"ナカタハンガーを作る中田工芸の歴史について、創業から現在までの軌跡をご紹介します。兵庫県豊岡での創業、全国への展開や東京ショールーム、海外との繋がりなど。",

//"metaDescProductCategoryMen"=>"ナカタハンガーの男性用商品一覧。スーツ、ジャケットからシャツ、ボトム、ネクタイ、ベルト用まで男性向けに上質な木製ハンガーを揃えています。肩先の厚みや湾曲が、洋服の型崩れを防ぎます。",
//"metaDescProductCategoryMenJacket"=>"ナカタハンガーのメンズジャケットハンガー一覧。コートやスーツ、ジャケット、アウターまで男性向けに上質な木製ハンガーを揃えています。肩先の厚みや湾曲が、洋服の型崩れを防ぎます。",
//"metaDescProductCategoryMenShirt"=>"ナカタハンガーのメンズシャツハンガー一覧。薄手のジャケット、Tシャツなどにもおすすめ。男性向けに上質な木製ハンガーを揃えています。シャツ用として適度な厚みがあり、洋服を立体的に美しく収納。",
//"metaDescProductCategoryMenBottom"=>"ナカタハンガーのメンズボトムハンガー一覧。ボトム全般、スラックスやズボン、パンツなどを美しく収納。",
//"metaDescProductCategoryMenNecktieBelt"=>"ナカタハンガーのネクタイ、ベルトハンガー。クローゼットに洋服と一緒に収納でき、男性向けの贈り物にも人気アイテムです。",

//"metaDescProductCategoryWomen"=>"ナカタハンガーの女性用商品一覧。スーツ、ジャケットからシャツ、ボトム、ストール、ベルト用まで女性向けに上質な木製ハンガーを揃えています。",
//"metaDescProductCategoryWomenJacket"=>"ナカタハンガーのレディスジャケットハンガー一覧。スーツ、ジャケット、コートまで女性向けに上質な木製ハンガーを揃えています。肩先の厚みや湾曲が、洋服の型崩れを防ぎます。",
//"metaDescProductCategoryWomenShirt"=>"ナカタハンガーのレディスシャツ、ブラウスハンガー一覧。ワンピースやカットソーにもおすすめ。女性向けに上質な木製ハンガーを揃えています。適度な厚みがあり、洋服を立体的に美しく収納。",
//"metaDescProductCategoryWomenBottom"=>"ナカタハンガーのレディスボトムハンガー一覧。ボトム全般、スカート、パンツなどを美しく収納。",
//"metaDescProductCategoryWomenStoleBelt"=>"ナカタハンガーのストール、マフラー、ベルトハンガー。簡単に美しく収納。ベルトハンガーは、1本1本かけることができスマートに保管します。",

//"metaDescProductCategoryOthersBrushShoehorn"=>"ナカタハンガーの洋服ブラシ、靴べらの商品一覧。ご家庭での毎日のお洋服のお手入れのほか、大切な人へのプレゼントとしてお勧め。",
//"metaDescProductCategoryOthersRackStand"=>"ナカタハンガーのハンガーラック、スタンド。お部屋のインテリアとしても映え、落ち着きと高級感を与えます。帽子や上着をかけたり、また来客用のクロークとしても役立ちます。企業の商談室や、ご家庭の玄関やリビングなどでおすすめです。",
//"metaDescProductCategoryOthersKimono"=>"ナカタハンガーの和装ハンガー。着物や浴衣、袈裟などに最適な形状の木製ハンガーです。桟が付いているので、帯と着物をセットして掛けることが可能。",
//"metaDescProductCategoryOthersKids"=>"ナカタハンガーのキッズハンガー。子供服のトップスやボトムスの収納に。なめらかで丸みのある可愛らしいデザインの木製ハンガーです。",
//"metaDescProductCategoryOthersPet"=>"ナカタハンガーのペットハンガー。愛犬のお洋服も木製ハンガーで揃えたいというご要望に答えてペットハンガーが誕生しました。ご家族同然のわんちゃんへ。首周りサイズ4種類から選択可能。",
//"metaDescProductCategoryOthersOthers"=>"ナカタハンガーの小物商品一覧。木製ハンガーの肩先に貼れる、服のずれ落ちを防ぐシートや、アパレルショップのディスプレイでよく見かけるＳフックをご案内。",

//"metaDescProductCategoryGift"=>"ナカタハンガーのギフト商品一覧。誕生日プレゼントや記念日やお祝いごとなどの、大切な人への贈り物に。おすすめの上質な木製ハンガーをご紹介します。",
//"metaDescProductCategoryGiftMen"=>"ナカタハンガーの男性用ギフト一覧。誕生日プレゼントや記念日やお祝いごとなどの、大切な人への贈り物に。おすすめの上質な木製ハンガーをご紹介します。",
//"metaDescProductCategoryGiftWomen"=>"ナカタハンガーの女性用ギフト一覧。誕生日プレゼントや記念日やお祝いごとなどの、大切な人への贈り物に。おすすめの上質な木製ハンガーをご紹介します。",
//"metaDescProductCategoryGiftPair"=>"ナカタハンガーの男女ペアギフト一覧。ご夫婦やご両親などに、お揃いで贈りたいという方へ。セットになっているので2人だけの特別な形のある贈り物に。",

//"metaDescProductSeriesNh"=>"ナカタハンガーのNH（エヌエイチ）シリーズ。特別な厚みのある一枚板から職人が一本一本削りだして作る”一本物つなぎ目のないハンガー”。人間の骨格に近いなめらかな丸みのある曲線を表現。",
//"metaDescProductSeriesAut"=>"ナカタハンガーのAuthentic（オーセンティック）シリーズ。国内外アパレルブランドやテーラーショップで採用された実績を持ち、品質にこだわって設計された機能的なデザインが強み。",
//"metaDescProductSeriesSet"=>"ナカタハンガーのSET（セット）シリーズ。ハイパフォーマンスな5本セットの木製ハンガー。同形状、同種類のハンガーを揃えたい方へ。シンプルながら基本的な機能を備えています。公式直販サイト限定販売商品。",

//"metaDescHelp"=>"The help page for NAKATA HANGER online shopping. Information about shipping fee.",
//"metaDescHelpFaq"=>"商品のことや、ハンガーってどう選べばいいの？など。オンラインショップのご利用についてお客様から多く寄せられるご質問を項目ごとにご紹介。",

"metaDescStores"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescAbout"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescCraftsmanship"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescCompany"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescHistory"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescHelp"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescPrivacyPolicy"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescShippingPolicy"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescRefundPolicy"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescLegal"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryMen"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryMenJacket"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryMenShirt"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryMenBottom"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryMenNecktieBelt"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryWomen"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryWomenJacket"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryWomenShirt"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryWomenBottom"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryWomenStoleBelt"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryOthersBrushShoehorn"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryOthersRackStand"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryOthersKimono"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryOthersKids"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescProductCategoryOthersPet"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",

//////////////////////////////////////////////////////////////////////////////////////////

//"hokkaido"=>"北海道",
//"tohoku"=>"東北",
//"kanto"=>"関東",
//"chubu"=>"中部",
//"kinki"=>"近畿",
//"chugoku"=>"中国",
//"shikoku"=>"四国",
//"kyushu"=>"九州",
//"okinawa"=>"沖縄",

//"hokkaido"=>"北海道",
//"aomori"=>"青森県",
//"iwate"=>"岩手県",
//"akita"=>"秋田県",
//"miyagi"=>"宮城県",
//"yamagata"=>"山形県",
//"fukushima"=>"福島県",
//"ibaraki"=>"茨城県",
//"tochigi"=>"栃木県",
//"gunma"=>"群馬県",
//"saitama"=>"埼玉県",
//"chiba"=>"千葉県",
"tokyo"=>"Tokyo",
//"kanagawa"=>"神奈川県",
//"yamanashi"=>"山梨県",
//"nagano"=>"長野県",
//"niigata"=>"新潟県",
//"toyama"=>"富山県",
//"ishikawa"=>"石川県",
//"fukui"=>"福井県",
//"shizuoka"=>"静岡県",
//"aichi"=>"愛知県",
//"gifu"=>"岐阜県",
//"mie"=>"三重県",
//"shiga"=>"滋賀県",
//"kyoto"=>"京都府",
//"osaka"=>"大阪府",
//"hyogo"=>"兵庫県",
//"nara"=>"奈良県",
//"wakayama"=>"和歌山県",
//"tottori"=>"鳥取県",
//"shimane"=>"島根県",
//"okayama"=>"岡山県",
//"hiroshima"=>"広島県",
//"yamaguchi"=>"山口県",
//"kagawa"=>"香川県",
//"ehime"=>"愛媛県",
//"tokushima"=>"徳島県",
//"kochi"=>"高知県",
//"fukuoka"=>"福岡県",
//"saga"=>"佐賀県",
//"nagasaki"=>"長崎県",
//"kumamoto"=>"熊本県",
//"oita"=>"大分県",
//"miyazaki"=>"宮崎県",
//"kagoshima"=>"鹿児島県",
//"okinawa"=>"沖縄県",

//"overseas"=>"海外",
//"otherOnlineShops"=>"その他オンラインショップ",

/*"dealers"=>array(
	"hokkaidoTohoku"=>array(
		array(
			"name"=>"丸井今井札幌本店",
			"prefecture"=>"北海道",
			"address"=>"札幌市中央区南1条西2丁目",
			"floor"=>"一条館 4F 紳士服",
			"tel"=>"011-205-1151",
			"map"=>"%E4%B8%B8%E4%BA%95%E4%BB%8A%E4%BA%95+%E6%9C%AD%E5%B9%8C%E6%9C%AC%E5%BA%97+%E4%B8%80%E6%9D%A1%E9%A4%A8/@43.0596655,141.352902,17z/data=!3m2!4b1!5s0x5f0b2982d67f29ab:0xcaa3eba46cc03b80!4m5!3m4!1s0x5f0b2982d680442f:0x8f6af94cfd95bc28!8m2!3d43.0596655!4d141.3550907",
		),
	),
),*/

);

?>