<?php

$texts = array(

"dot"=>"・",
"dotSlash"=>"・",
","=>"、",
"asterist"=>"※",
"("=>"（",
")"=>"）",
"["=>"【",
"]"=>"】",
"leftBracket"=>"「",
"rightBracket"=>"」",

"man"=>"万",
"yen"=>"円",
"includingTax"=>"税込",
"productCountUnit"=>"件",
"mei"=>"名",

"year"=>"年",
"month"=>"月",

"sun"=>"日",
"mon"=>"月",
"tue"=>"火",
"wed"=>"水",
"thu"=>"木",
"fri"=>"金",
"sat"=>"土",

"sun."=>"日曜",
"sat."=>"土曜",

"friday"=>"金曜日",

"all"=>"すべて",

"holiday"=>"祝祭日",
"sunHoliday"=>"日曜・祝祭日",

"shuheiNakata"=>"中田修平",

"back"=>"戻る",
"toPrev"=>"前へ",
"toNext"=>"次へ",

"check-"=>"を見る",

"required"=>"必須",

//////////////////////////////////////////////////////////////////////////////////////////

"notFound"=>"見つかりませんでした",
"pageNotFound"=>"ページが見つかりませんでした",

//////////////////////////////////////////////////////////////////////////////////////////

"nakatahanger"=>"NAKATA HANGER",

"aHomeForYourClothes"=>"洋服の帰る場所",
"aHomeForYourClothes2"=>"A Home for Your Clothes",
//"aHomeForYourClothesMessage1"=>"人に帰る家があるように 洋服にも帰る場所があります。",
//"aHomeForYourClothesMessage2"=>"季節の移ろいとともに 心を躍らせてくれる大切な洋服。",
//"aHomeForYourClothesMessage3"=>"木のぬくもりを感じながら 次の出番をここで待っています。",
"aHomeForYourClothesMessage"=>"人に帰る家があるように 洋服にも帰る場所があります。<br>季節の移ろいとともに 心を躍らせてくれる大切な洋服。<br>木のぬくもりを感じながら 次の出番をここで待っています。",

"products"=>"商品",
"products2"=>"Products",
"gift"=>"ギフト",
"showroom"=>"ショールーム",
"showroom2"=>"Showroom",
"stores"=>"店舗",
"howToChoose"=>"ハンガーの選び方",
"howToChoose2"=>"How to choose",
"navi"=>"公式ラインアカウント",

"home"=>"ホーム",
"backToHome"=>"ホームに戻る",
"myPage"=>"マイページ",
"companyInfo"=>"会社概要",
"search"=>"検索",
"webGuide"=>"ご利用ガイド",
"faq"=>"よくあるご質問",
"faqen"=>"海外販売について",
"spelling"=>"ネーム入れFAQ",
"inquiry"=>"お問い合わせ",
"privacyPolicy"=>"プライバシーポリシー",
"legal"=>"特定商取引法に基づく表記",
"japanese"=>"日本語",
"english"=>"ENGLISH",
"blog"=>"ブログ",
"blog2"=>"Blog",

"men2"=>"Men",
"women2"=>"Women",
"forMen"=>"男性用",
"forWomen"=>"女性用",
"productListForMen"=>"男性用商品一覧",
"productListForWomen"=>"女性用商品一覧",
"jacketHanger"=>"ジャケットハンガー",
"shirtHanger"=>"シャツハンガー",
"bottomHanger"=>"ボトムハンガー",
"necktieBeltHanger"=>"ネクタイ / ベルトハンガー",
"stoleBeltHanger"=>"ストール / ベルトハンガー",
"others"=>"その他",
"clothBrush"=>"洋服ブラシ",
"shoehorn"=>"靴べら",
"hangerRack"=>"ハンガーラック",
"stand"=>"スタンド",
"kimonoHanger"=>"和装ハンガー",
"wajimaHanger"=>"輪島塗ハンガー",
"kidsHanger"=>"キッズハンガー",
"petHanger"=>"ペットハンガー",
"otherAccessories"=>"その他の小物",
"outletHanger"=>"アウトレット",
"series"=>"シリーズ",
"bySeries"=>"シリーズ別",
"nhSeries"=>"NH",
"autSeries"=>"Authentic",
"setSeries"=>"SET",
"option"=>"オプション",
"nameEngraving"=>"ネーム入れ",
"sampleLending"=>"サンプル貸出",

"jacket2"=>"Jacket",
"shirt2"=>"Shirt",
"bottom2"=>"Bottom",
"others2"=>"Others",

"gift2"=>"Gift",
"productListForGift"=>"ギフト商品一覧",
"giftForMen"=>"男性に贈る",
"giftForWomen"=>"女性に贈る",
"giftForBoth"=>"男女ペアで贈る",
"weddingGift"=>"引出物",
"familyCelebration"=>"内祝い",
"bridal"=>"ブライダル",
"movingToSpecialSite"=>"特設サイトに移動します",
"graduationGift"=>"卒業記念品",
"graduationTitle"=>"福（服）をかける卒業記念品ハンガーのNAKATA HANGER",
"menshangerset01"=>"メンズスーツハンガーセット SET-01",
"schoolYear"=>"年度",
"gradGift"=>"卒業記念",
"forOrg"=>"法人記念品・ノベルティ",
"forOrgTitle"=>"福（服）をかける企業・法人向け記念品のNAKATA HANGER",
"furusato"=>"ふるさと納税 特設サイト",
"consideringOrgGift"=>"法人記念品用にご検討されている企業様",
"giftDesc1"=>"使ってみて本当に良いものは、大切な人にも贈りたい。",
"giftDesc2"=>"上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。",

"aboutNameEngraving"=>"ネーム入れについて",
"nameEngraving2"=>"Name Engraving",

"news"=>"お知らせ",
"news2"=>"News",
"media"=>"メディア",
"journal"=>"ジャーナル",
"backToNewsList"=>"News 一覧に戻る",

"about"=>"NAKATA HANGER とは",
"about2"=>"About",
"concept2"=>"Concept",
"conceptMainText"=>"人に帰る家があるように洋服にも帰る場所があります。<br>季節の移ろいとともに心を踊らせてくれる大切な洋服。<br>木のぬくもりを感じながら次の出番をここで待っています。",
//"conceptMainText"=>"<div><span>人に帰る家があるように</span><span>洋服にも帰る場所があります。</span></div><div><span>季節の移ろいとともに</span><span>心を踊らせてくれる大切な洋服。</span></div><div><span>木のぬくもりを感じながら</span><span>次の出番をここで待っています。</span></div>",
"conceptSubText"=>"<p>中田工芸株式会社は 1946 年の創業以来、絶えず変化し成長するファッション文化の中で、日本のアパレル企業の非常に高い要求レベルに応え続けてきた国内唯一の木製ハンガー専業メーカーです。NAKATA HANGER とは、そんな中田工芸がユーザー視点でハンガーを見つめ直し、今まで蓄えてきた技術と知識と経験を最大限に発揮してこだわり抜いた Made in Japan の木製ハンガーです。職人の技によって1本1本生み出されるハンガーは、「無駄のないデザイン」と「洋服のシルエットを保つための機能」を併せ持ちます。そこには、時代を経ても変わることのない普遍性が存在します。</p><p>ギフトでも幅広く利用されるのも NAKATA HANGER の特徴です。大切な人への贈り物として、結婚式の引出物としても好評をいただいています。そこには「ふくをかける」という願い、つまり洋服だけでなく幸福もかけてほしいというコンセプトがあります。贈る人や使う人が幸せになってほしいという思いを込めて、職人が一本一本丁寧に手作業で作っているから、ぬくもりのあるハンガーになっています。</p><p>私たちはハンガーの可能性を追い求め、その魅力を世界に発信し続けると同時に、木製ハンガーを通じて心豊かな暮らしを提案していきます。</p>",
"brandHistory"=>"NAKATA HANGER の歴史",
"brandHistory2"=>"Brand History",
"craftsmanship"=>"ものづくり",
"craftsmanship2"=>"Craftsmanship",
"craftsmanshipTitle"=>"最高のハンガーを届ける",
"craftsmanshipMainText"=>"私達の技術やこだわりは、さまざまな形があります。</p><p>ひとつめは、もちろんハンガーという製品にたいするこだわり。洋服にとって良いか、またそれを使うお客様にとって良いかを常に考えて生産しています。ハンガーのフォルムを生み出す成型と磨き、そして奥深い表情を引き出すための塗装の技術を常に追求しています。</p><p>ふたつめは、木製品としてのこだわり。人間に個性があるように、木にも1本1本特徴があります。硬さや風合い、木目のばらつきを職人の目で見極めながら、自然な仕上がりになるように木と語りながらハンガーを作っています。",
"craftsmanshipSubTitle"=>"材料へのこだわり",
"craftsmanshipSubText"=>"NAKATA HANGER 製品は主にヨーロッパ産のブナ材を使用しています。適度な硬さを持ち、均質で安定しているブナは、古くからハンガーに使用されています。<br>技術的には他の木材でもハンガーは製造できますが、ヤニや反りが多い針葉樹だと大切な洋服や生地を痛めてしまいます。広葉樹でも重すぎたり木目が強すぎると使いやすさや美しさが損なわれてしまいます。<br>丁寧に磨くことで滑らかな仕上がりになるブナは、洋服をかけるハンガーにとって最も適した木材です。",
"forEnvironment"=>"環境への配慮",
"sustanableEnronment"=>"持続可能な環境を",
"enronmentMainText"=>"豊かな森を維持するために、無計画な伐採ではなく、すべて計画的な植林及び伐採のルールの元で管理された木材を仕入れています。<br>計画的に伐採が行われることで森林内に適度な光が射し込み、下層植生が繁茂します。それにより多くの生物が生息できるようになります。また、幹が太くなることで風雪に強い森林となり、水源かん養機能や土砂流出防止機能も向上します。<br>このサイクルが成り立つことで、森や地球の環境が保たれます。次世代の未来につなげていくためには、持続可能な環境や社会があるからこそと考えています。",
"production"=>"製品づくり",
"environmentSubText1"=>"大きいハンガーを作る際に出る端材から小さいハンガーを、小さいハンガーの端材からパンツハンガーを、さらにその端材からクラフト製品を製作し、貴重な自然資源を無駄なく最大限有効活用します。",
"energyUse"=>"エネルギー利用",
"environmentSubText2"=>"製品に至らないほどの小さな端材は、成型中に出るオガクズと共に工場のエネルギー源として活用します。焼却炉で燃やし、ボイラーで蒸気を発生させることで塗装の乾燥室、曲げ木の加工、暖房に利用しています。",
"moreUse"=>"さらなる活用",
"environmentSubText3"=>"さらに焼却炉に残った「灰」も利用します。兵庫県の本社が位置する但馬地方の特産品「栃餅」は、作る際のアク抜きに広葉樹の灰が利用されます。端材を燃やすことでできた灰を、地元特産品の生産のために提供しています。",
"companyInfo"=>"企業情報",
"company2"=>"Company",
"message2"=>"Message",
"presidentMessageTitle"=>"世界一満足していただけるハンガーを届けたい。",
"presidentMessage"=>"中田工芸は1946年、創業者である中田敏雄と木製ハンガー職人との出会いからその歴史が始まりました。以後、戦後の復興、高度成長時代を通じて、店舗などの業務用ハンガーを主としてファッション業界に貢献してまいりました。その過程でなによりも大切にしてきたのは顧客からの信頼を守ることです。品質を重視し、別注デザインに対応する技術、納期を遵守する生産管理の構築でした。こうした企業文化は、自社ブランド「NAKATA HANGER」の展開へも引き継がれ、一般のお客様からも評価をいただくようになりました。</p><p>私は長年にわたり日本で作り続けてきた自社の製品には世の中に知られていない可能性があると感じましたので、少しでも多くの人にその価値を伝えたいと思い、試行錯誤を繰り返してきました。その結果分かったことは、我が社のハンガーが持っている可能性は自分の想像を遥かに超えていたということです。ハンガーというもの（製品）を通じて、多くの感動や人との出会いに恵まれていることに驚くと共に、感謝の念に堪えません。</p><p>中田工芸の経営理念は「挑戦し、成長する」。ハンガーを通して、まだ見ぬ出会いや出来事に期待を膨らませていますが、そのためには常に新しいことにチャレンジし続けてこそです。100年企業へ向けて、これからも挑戦を続け、社会のお役に立てるように努力を重ねて参ります。",
"president"=>"代表取締役社長",
"companyName"=>"社名",
"nakatakogeiCompany"=>"中田工芸株式会社",
"foundation"=>"創業",
"showa"=>"昭和",
"heisei"=>"平成",
"reiwa"=>"令和",
"businessDesc"=>"事業内容",
"presidentPerson"=>"代表者",
"location"=>"所在地",
"capital"=>"資本金",
"employee"=>"従業員",
"mainBank"=>"主要取引銀行",
"companyHistory"=>"会社の歴史",
"companyHistory2"=>"Company History",

"sdgsActions"=>"SDGs の取り組み",
"nhBrandHistory"=>"ブランドヒストリー",

"recruit"=>"採用情報",

"orderFlow"=>"ご注文の流れ",
"aboutShippingFee"=>"送料について",
"aboutPaymentMethod"=>"支払い方法について",
"aboutShoppingPoint"=>"ショッピングポイントについて",
"aboutWrappingPackage"=>"ラッピング・梱包について",
"aboutNoshi"=>"のしについて",
"aboutReceiptDetails"=>"領収書・明細書について",

"viewAll"=>"View all",
"readMore"=>"Read more",
"productDetails"=>"Product details",

"concierge2"=>"Concierge",
"conciergeService"=>"コンシェルジュ・サービス",

"feature"=>"特集",
"feature2"=>"Feature",
"features"=>"Features",

"saleEnded"=>"販売終了しました",

"series2"=>"series",
"ranking2"=>"Ranking",
"customer2"=>"Customer",
"information2"=>"Information",
"others2"=>"Others",
"access2"=>"access",
"map2"=>"map",
"open2"=>"open",
"close2"=>"close",

"sortBy"=>"",
"lineupOrder"=>"ラインナップ順",
"ascPriceOrder"=>"価格が安い順",
"descPriceOrder"=>"価格が高い順",

"sizeSelectable"=>"サイズ選択可",

"soldOut"=>"現在 売り切れ中",
"seriesDescNh"=>"NH シリーズは特別な厚みの一枚の板から職人が削り出して作るつなぎ目のない最高級モデルのハンガーです。<br>襟元を上品に演出する「トレンチ」が共通のデザイン。全て職人による手作業で作られる「究極」の１本です。",
"seriesDescAut"=>"オーセンティックは幅広い目的に応じてお選びいただける、利便性の高いシリーズです。<br>さまざまなアパレルブランドで採用された実績を持ち、ディテールと品質にこだわって設計された機能的なデザインが特徴。",
"seriesDescSet"=>"SET シリーズは国産の品質の高さを維持しながら、価格を抑えたリーズナブルな NAKATA HANGER 入門モデルです。<br>安心して、気軽におしゃれを楽しむための基本的な機能を備えた５本組となっています。",

//"seriesDescNh1"=>"<span>NHコレクションは、二つの木を中央で繋いで作る通常のハンガーとは異なり、特別な厚みの一枚の板から職人が削り出して作るつなぎ目のないハンガーです。</span><span>襟元を上品に演出する“トレンチ”（溝、または掘り）が共通のデザインです。</span><span>ハンガー背面には、NAKATA HANGERロゴではなくNHコレクションのみ許される「NHロゴ」が入っています。</span>",
"seriesDescNh1"=>"<span>NHコレクションは、二つの木を中央で繋いで作る通常のハンガーとは異なり、</span><span>特別な厚みの一枚の板から職人が削り出して作るつなぎ目のないハンガーです。",
"seriesDescNh2"=>"特別な厚みの板が必要な理由、それは深い湾曲を作るため。<br>洋服は人体にフィットするよう裁断されています。なので収納時はヒトが着ている状態を維持するのがベストです。<br>ハンガーに求められるのは首、肩、そして背中の骨格にいかに近づけるか。<br>その首から背中にかけてのラウンドを表現するためには、1枚の板から削り出す方法が最も有効なのです。<br><br>職人の手作業で生み出されるなめらかな丸み。<br>素材は天然ブナ材。ヨーロッパで育ち、計画的に栽培されたもののみを使用しています。<br>天然木は均一な人工材料とは違い、木目や節、繊維の向きがそれぞれ違います。 一枚板から削り出す「一本物」であればなおさらのこと。<br>それらを熟練の職人が見極め、その材木に合わせた方法で削り出して行きます。",
"seriesDescAut1"=>"<span>ディテールと品質にこだわって設計された機能的なデザイン、</span><span>確かな技術と実績に裏打ちされた一流のハンガーがここに集いました。</span>",
"seriesDescAut2"=>"オーセンティックシリーズは、幅広い目的に応じてお選びいただける、利便性の高いコレクションです。さまざまなアパレルブランドで採用された実績をもち、ディテールと品質にこだわって設計された機能的なデザインが特徴です。<br><br>&lt;Authentic = 本物の、信ずべき、確実な、典拠のある&gt;",
"seriesDescSet1"=>"<span>同じハンガーの5本組で、お部屋の収納がセレクトショップの雰囲気に変わります。</span><span>安心して、気軽におしゃれを楽しむための基本的な機能を備えた5本組になっています。</span>",
//"seriesDescSet1"=>"<span>国産ハンガーを５本セットでリーズナブルに</span><span>お部屋をセレクトショップ風に変身させる５本組</span><span>機能的なハンガーを保ちながら。<br>出来る限りシンプルな形状にすることで手軽にハンガーを揃えていただけます。</span><span>品質の違いを知っていただける機会に。<br>ヨーロッパ地域で計画伐採されたブナ材を使用し、成形から塗装・組立・梱包までのすべてを日本国内工場（兵庫県豊岡市）で一貫して行なっています。</span><span>同じハンガーを５本単位で。<br>同じ形状のハンガーを揃えることでの収納性の良さ、見た目の美しさを実感いただけます。</span>",
"seriesDescSet2"=>"国産ハンガーを５本セットでリーズナブルに。お部屋をセレクトショップ風に変身させる５本組。<br><br><a href='".getHref("howto")."#q4' style='color:dodgerblue;'>※生産国:日本(兵庫県)、ヨーロッパ産ブナ材を使用</a><br><br><span style='font-weight:bold;'>表示価格は5本組価格です。</span>",

"registerMailMagazine"=>"メールマガジンの登録",
"sendingNewProductsAndCampaign"=>"新商品やキャンペーン情報をお届けいたします",
"emailAddress"=>"メールアドレス",
"subscription"=>"購読",

"videoHasSound"=>"再生すると音が出ます",
//////////////////////////////////////////////////////////////////////////////////////////

//"categoryMen"=>"男性用のキャッチコピー ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯◯",
//"categoryMenJacket"=>"男性用ジャケットのキャッチコピー ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯ ◯◯ ◯◯◯<br>◯◯◯ ◯◯ ◯◯ ◯◯◯ ◯◯ ◯◯◯ ",
//"categoryOthersKids"=>"子供の服も、できれば気持ちよくすっきりと収納したい。<br>それも毎日のことだから、分かりやすく探しやすく。<br>子どもにとっても日々の習慣になったら嬉しいな・・・<br><br>親も子どもも愉しめるハンガーを揃えました。",
"categoryGift"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",
"categoryGiftMen"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",
"categoryGiftWomen"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",
"categoryGiftPair"=>"<h2>贈る喜び、贈られる喜び。</h2><br>普段の生活の中では購入する機会がなくても、デザイン性と実用性を兼ねた品質のよい贈り物は、本当に嬉しいもの。<br>使ってみて本当に良いものは、大切な人にも贈りたい。<br>上質な木製ハンガーは、温かい感触だけでなく、機能・造形美ともに備えた毎日使うワンランク上のアイテムです。<br>オリジナリティある贈り物として、お洒落なあの方にもきっと喜んで頂けます。",

//////////////////////////////////////////////////////////////////////////////////////////

"country"=>"国",
"japan"=>"日本",

"zipMark"=>"〒",
"tel"=>"Tel",
"fax"=>"Fax",

"prefecture"=>"都道府県",
"city"=>"都市",
"address"=>"住所",
"telNum"=>"電話番号",
"businessHours"=>"営業時間",

"headquarters"=>"本社",
"hqAddr"=>"兵庫県豊岡市日高町江原92",

"byCar"=>"車でお越しの方",
"byTrain"=>"電車でお越しの方",
"wayToHqByCar"=>"北近畿豊岡自動車道<br>日高神鍋高原 IC 出口より約5分",
"wayToHqByTrain"=>"JR山陰線「江原駅」から徒歩約１分",

"aoyama"=>"青山",
"aoyamaShowroom"=>"青山ショールーム",
//"srZip"=>"107-0062",
"srAddr"=>"東京都港区南青山1-1-1",
"srBuilding"=>"新青山ビル西館 1F",
"visitingReservation"=>"来店予約",

"nearestStation"=>"最寄り駅",
"aoyamaIcchome"=>"青山一丁目",
"station"=>"駅",
"3-4exit"=>"3・4番出口",
"tokyoMetro"=>"東京メトロ",
"ginzaLine"=>"銀座線",
"hanzomonLine"=>"半蔵門線",
"toeiSlashOedoLine"=>"都営 / 大江戸線",
"dutyfree"=>"※免税手続き可",

"woodenHanger"=>"木製ハンガー",
"displayAccessories"=>"ディスプレイ什器",
"interior"=>"インテリア",
"productionOfWoodenCrafts"=>"木製クラフトの製造及び販売",

"tajimaBank"=>"但馬銀行",
"tajimaShinkinBank"=>"但馬信用金庫",
"smbc"=>"三井住友銀行",

"name"=>"お名前",
"inquiryContents"=>"お問い合わせ内容",
"enterText"=>"ご記入下さい",
"enterForConfirmation"=>"ご記入下さい（確認用）",
"confirmInquiry"=>"送信内容を確認",
"pleaseEnter"=>"記入してください",
"enterPhoneFormat"=>"電話番号の形式で記入してください",
"enterEmailFormat"=>"メールアドレスの形式で記入してください",
"emailsNotMatched"=>"確認用のメールアドレスが一致していません",
"okToSendFollowing"=>"以下の内容で送信してよろしいですか?",
"send"=>"送信する",

"inquiryThankYou"=>"お問い合わせを受け付けました。",
"inquiryThankYouTexts"=>"この度は NAKATA HANGER へお問い合わせいただき誠にありがとうございます。<br>ご入力いただいたメールアドレス宛てに担当者からご連絡いたしますのでしばらくお待ちください。<br><br>弊社からの返信が迷惑メールに振り分けられる場合がございます。<br>メールアドレス（".EMAIL_INQUIRY."）をセーフリストにお入れくださいますようよろしくお願いいたします。",
"inquiryFailed"=>"フォームの送信が失敗しました。",
"inquiryFailedTexts"=>"誠に申し訳ございませんが、フォームを正常に送信できませんでした。<br>大変お手数ですが、下記の電話番号よりお問い合わせください。",
"inquiryTel"=>"お問い合わせ電話番号",

"thankYouInquiry"=>"お問い合わせありがとうございます",

"showMore"=>"続きを読む",
"backToList"=>"一覧に戻る",
"instagramDesc"=>"Instagram で #NAKATAHANGER のハッシュタグ投稿されている写真を紹介しています。<br device='pc'>紹介時には、SNS スタッフからご連絡させていただきます。たくさんの投稿をお待ちしています。",
"inquiryAboutContents"=>"コンテンツに関するお問い合わせ",
"inquiryAboutInstagramContents"=>"Instagram のコンテンツに関するお問い合わせ",
"inquiryInstagramDesc"=>"Instagram のコンテンツに関するお問い合わせ（ご自身で所有するコンテンツの掲載停止依頼など）は下記のフォームよりお送りください。",
"instagramContent"=>"お問い合わせに<br device='pc'>関するコンテンツ",

//////////////////////////////////////////////////////////////////////////////////////////

"showroomDesc"=>"ハンガーを手にとって触れていただき、その感触、色、フォームの数々を感じて頂きたい。是非、大切にしたいお気に入りの一着を持って、青山ショールームへお越し下さい。<br>かける衣服のサイズ、いろいろなシーン・・・<br>皆様のご希望に添う、とっておきのハンガーとの出会いをお手伝いいたします。スタッフ一同、心よりお待ちしております。",

"officialOnlineShop"=>"直営オンラインショップ",
"nhcomDesc"=>"兵庫・豊岡の自社工場で製造した NAKATA HANGER ですべての商品を販売しています。<br>ハンガーへの名入れやギフトラッピングも承ります。",

"exclusiveService"=>"限定特典",
"nhcomSpecial1"=>"ご注文金額 ".number_format(tax(FREE_SHIPPING_PRICE_WITHOUT_TAX))." 円（税込）以上で送料無料",
"nhcomSpecial2"=>"ご注文金額 100 円ごとに 1 ポイント",
"nhcomSpecial3"=>"初回購入時に 300 ポイントをプレゼント",
"nhcomSpecial4"=>"WEB 限定商品「<a href='".getHref("set")."' nh-link-color>SET シリーズ</a>」",

"dealingStores"=>"取扱店舗",
"dealingStoresDesc"=>"店舗によって取り扱い商品が異なります。<br>
取り扱い商品の詳細についてのお問い合わせは各店舗にお問い合わせください。<br>
※SETシリーズは、直営店のみの販売しております。<br>
（東京青山ショールーム、nakatahanger.com、楽天、Amazon）にてお買い求めください。
<br><br>",

"productionDelay"=>"<div>生産遅延の為、百貨店、お取り扱い店舗、当サイトで一時販売を休止している商品がございます。<br device='pc'>誠に恐れ入りますが、店舗・商品によっては商品品切れの場合がございますので予めご了承ください。<br device='pc'>（※在庫が無い場合、お取り寄せ対応も承れませんのでご了承ください。）</div><span style=color:black;>詳細は</span><a href=https://www.nakatahanger.com/news/4141><span style=color:blue;>コチラ</span></a>",

//////////////////////////////////////////////////////////////////////////////////////////

"metaKeywordsCommon"=>"中田ハンガー,ナカタハンガー,NAKATAHANGER,中田工芸,木製ハンガー,woodenhanger",

"metaDescTop"=>"ナカタハンガーの公式サイト。国内唯一の木製ハンガーメーカーが、上質で豊かな暮らしを提案するハンガーブランド。 The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",
"metaDescEnglish"=>"The official site of NAKATA HANGER. Luxury wooden hangers made in Japan with our passion and craftsmanship for a sophisticated lifestyle.",

"metaDescStores"=>"ナカタハンガーの東京青山ショールームや取扱店舗のご案内。木製ハンガーの肌触りや色、フォームの数々を手にとって直接触れてお確かめください。",
"metaDescNews"=>"商品、イベントやメディア掲載などの NAKATA HANGER の最新ニュースをお知らせします。",
"metaDescHowTo"=>"最適な木製ハンガーを選ぶためのポイント。スーツやジャケット、シャツ、ボトム等の洋服に合う肩幅のサイズや使い方、収納や保管のコツをお伝えします。",
"metaDescNavi"=>"納期の確認、名入れについて、ハンガーの大きさや色味について、引き出物のご相談、卒業記念のｶﾀﾛｸﾞ送付のご依頼など。",
"metaDescGraduation"=>"小学校・中学校・高校の卒業の門出に、ずっと使える記念品を。国内唯一の木製ハンガー専業メーカーのナカタハンガー。一年保証付き。校章や学校名を刻印できます。",
// "metaDescNovelty"=>'法人企業や店舗の創立周年記念やオープン祝いの、贈り物やノベルティに。名入れ（ネーム入れ）やロゴ入れで、オリジナル木製ハンガーを承ります。大切な記念に"ふくをかける"ハンガーを。',
"metaDescNovelty"=>'ロゴ入れや名入れで、オリジナルの木製ハンガーを中田工芸がお作りします。創立記念・周年記念、イベントノベルティーやグッズに「ふくをかける」ハンガーを。',
"metaDescFuru"=>'ふるさと納税の返礼品で、NAKATA HANGERが貰えます。',
"metaDescPrivacyPolicy"=>"ナカタハンガーのプライバシーポリシー「個人情報」についてご案内。",
"metaDescLegal"=>"ナカタハンガーの公式通販サイトの特定商取引法に基づく表記ページ。",

"metaDescAbout"=>"ナカタハンガーのコンセプトやブランドの歴史をお伝えします。職人の技によって1本1本生み出されるこだわり抜いた Made in Japan の木製ハンガー。ご自宅用、ギフト、引出物等、ハンガーを通じて心豊かな暮らしを提案します。",
"metaDescCraftsmanship"=>"最高の木製ハンガーを届けるための私達のこだわりについて。木と向き合う職人の技術、ブナ材のこと、そして持続可能な環境（サステナビリティ）への取り組みをお伝えします。",
"metaDescCompany"=>"「世界一満足していただけるハンガーを届けたい。」との想いのもと、国内のみならず海外販売を行っています。会社概要、社長メッセージ、ビジョン、企業理念をお伝えします。",
"metaDescHistory"=>"ナカタハンガーを作る中田工芸の歴史について、創業から現在までの軌跡をご紹介します。兵庫県豊岡での創業、全国への展開や東京ショールーム、海外との繋がりなど。",

"metaDescProductCategoryMen"=>"ナカタハンガーの男性用商品一覧。スーツ、ジャケットからシャツ、ボトム、ネクタイ、ベルト用まで男性向けに上質な木製ハンガーを揃えています。肩先の厚みや湾曲が、洋服の型崩れを防ぎます。",
"metaDescProductCategoryMenJacket"=>"ナカタハンガーのメンズジャケットハンガー一覧。コートやスーツ、ジャケット、アウターまで男性向けに上質な木製ハンガーを揃えています。肩先の厚みや湾曲が、洋服の型崩れを防ぎます。",
"metaDescProductCategoryMenShirt"=>"ナカタハンガーのメンズシャツハンガー一覧。薄手のジャケット、Tシャツなどにもおすすめ。男性向けに上質な木製ハンガーを揃えています。シャツ用として適度な厚みがあり、洋服を立体的に美しく収納。",
"metaDescProductCategoryMenBottom"=>"ナカタハンガーのメンズボトムハンガー一覧。ボトム全般、スラックスやズボン、パンツなどを美しく収納。",
"metaDescProductCategoryMenNecktieBelt"=>"ナカタハンガーのネクタイ、ベルトハンガー。クローゼットに洋服と一緒に収納でき、男性向けの贈り物にも人気アイテムです。",

"metaDescProductCategoryWomen"=>"ナカタハンガーの女性用商品一覧。スーツ、ジャケットからシャツ、ボトム、ストール、ベルト用まで女性向けに上質な木製ハンガーを揃えています。",
"metaDescProductCategoryWomenJacket"=>"ナカタハンガーのレディスジャケットハンガー一覧。スーツ、ジャケット、コートまで女性向けに上質な木製ハンガーを揃えています。肩先の厚みや湾曲が、洋服の型崩れを防ぎます。",
"metaDescProductCategoryWomenShirt"=>"ナカタハンガーのレディスシャツ、ブラウスハンガー一覧。ワンピースやカットソーにもおすすめ。女性向けに上質な木製ハンガーを揃えています。適度な厚みがあり、洋服を立体的に美しく収納。",
"metaDescProductCategoryWomenBottom"=>"ナカタハンガーのレディスボトムハンガー一覧。ボトム全般、スカート、パンツなどを美しく収納。",
"metaDescProductCategoryWomenStoleBelt"=>"ナカタハンガーのストール、マフラー、ベルトハンガー。簡単に美しく収納。ベルトハンガーは、1本1本かけることができスマートに保管します。",

"metaDescProductCategoryOthersBrushShoehorn"=>"ナカタハンガーの洋服ブラシ、靴べらの商品一覧。ご家庭での毎日のお洋服のお手入れのほか、大切な人へのプレゼントとしてお勧め。",
"metaDescProductCategoryOthersRackStand"=>"ナカタハンガーのハンガーラック、スタンド。お部屋のインテリアとしても映え、落ち着きと高級感を与えます。帽子や上着をかけたり、また来客用のクロークとしても役立ちます。企業の商談室や、ご家庭の玄関やリビングなどでおすすめです。",
"metaDescProductCategoryOthersKimono"=>"ナカタハンガーの和装ハンガー。着物や浴衣、袈裟などに最適な形状の木製ハンガーです。桟が付いているので、帯と着物をセットして掛けることが可能。",
"metaDescProductCategoryOthersKids"=>"ナカタハンガーのキッズハンガー。子供服のトップスやボトムスの収納に。なめらかで丸みのある可愛らしいデザインの木製ハンガーです。",
"metaDescProductCategoryOthersPet"=>"ナカタハンガーのペットハンガー。愛犬のお洋服も木製ハンガーで揃えたいというご要望に答えてペットハンガーが誕生しました。ご家族同然のわんちゃんへ。首周りサイズ4種類から選択可能。",
"metaDescProductCategoryOthersOthers"=>"ナカタハンガーの小物商品一覧。木製ハンガーの肩先に貼れる、服のずれ落ちを防ぐシートや、アパレルショップのディスプレイでよく見かけるＳフックをご案内。",

"metaDescProductCategoryGift"=>"ナカタハンガーのギフト商品一覧。誕生日プレゼントや記念日やお祝いごとなどの、大切な人への贈り物に。おすすめの上質な木製ハンガーをご紹介します。",
"metaDescProductCategoryGiftMen"=>"ナカタハンガーの男性用ギフト一覧。誕生日プレゼントや記念日やお祝いごとなどの、大切な人への贈り物に。おすすめの上質な木製ハンガーをご紹介します。",
"metaDescProductCategoryGiftWomen"=>"ナカタハンガーの女性用ギフト一覧。誕生日プレゼントや記念日やお祝いごとなどの、大切な人への贈り物に。おすすめの上質な木製ハンガーをご紹介します。",
"metaDescProductCategoryGiftPair"=>"ナカタハンガーの男女ペアギフト一覧。ご夫婦やご両親などに、お揃いで贈りたいという方へ。セットになっているので2人だけの特別な形のある贈り物に。",

"metaDescProductSeriesNh"=>"ナカタハンガーのNH（エヌエイチ）シリーズ。特別な厚みのある一枚板から職人が一本一本削りだして作る”一本物つなぎ目のないハンガー”。人間の骨格に近いなめらかな丸みのある曲線を表現。",
"metaDescProductSeriesAut"=>"ナカタハンガーのAuthentic（オーセンティック）シリーズ。国内外アパレルブランドやテーラーショップで採用された実績を持ち、品質にこだわって設計された機能的なデザインが強み。",
"metaDescProductSeriesSet"=>"ナカタハンガーのSET（セット）シリーズ。ハイパフォーマンスな5本セットの木製ハンガー。同形状、同種類のハンガーを揃えたい方へ。シンプルながら基本的な機能を備えています。公式直販サイト限定販売商品。",

"metaDescHelp"=>"ナカタハンガーのご利用ガイド。ご注文の流れ、送料、支払い方法、ショッピングポイント、ラッピング・梱包等についてご案内。",
"metaDescHelpFaq"=>"商品のことや、ハンガーってどう選べばいいの？など。オンラインショップのご利用についてお客様から多く寄せられるご質問を項目ごとにご紹介。",

//////////////////////////////////////////////////////////////////////////////////////////

"hokkaido"=>"北海道",
"tohoku"=>"東北",
"kanto"=>"関東",
"chubu"=>"中部",
"kinki"=>"近畿",
"chugoku"=>"中国",
"shikoku"=>"四国",
"kyushu"=>"九州",
"okinawa"=>"沖縄",

"hokkaido"=>"北海道",
"aomori"=>"青森県",
"iwate"=>"岩手県",
"akita"=>"秋田県",
"miyagi"=>"宮城県",
"yamagata"=>"山形県",
"fukushima"=>"福島県",
"ibaraki"=>"茨城県",
"tochigi"=>"栃木県",
"gunma"=>"群馬県",
"saitama"=>"埼玉県",
"chiba"=>"千葉県",
"tokyo"=>"東京都",
"kanagawa"=>"神奈川県",
"yamanashi"=>"山梨県",
"nagano"=>"長野県",
"niigata"=>"新潟県",
"toyama"=>"富山県",
"ishikawa"=>"石川県",
"fukui"=>"福井県",
"shizuoka"=>"静岡県",
"aichi"=>"愛知県",
"gifu"=>"岐阜県",
"mie"=>"三重県",
"shiga"=>"滋賀県",
"kyoto"=>"京都府",
"osaka"=>"大阪府",
"hyogo"=>"兵庫県",
"nara"=>"奈良県",
"wakayama"=>"和歌山県",
"tottori"=>"鳥取県",
"shimane"=>"島根県",
"okayama"=>"岡山県",
"hiroshima"=>"広島県",
"yamaguchi"=>"山口県",
"kagawa"=>"香川県",
"ehime"=>"愛媛県",
"tokushima"=>"徳島県",
"kochi"=>"高知県",
"fukuoka"=>"福岡県",
"saga"=>"佐賀県",
"nagasaki"=>"長崎県",
"kumamoto"=>"熊本県",
"oita"=>"大分県",
"miyazaki"=>"宮崎県",
"kagoshima"=>"鹿児島県",
"okinawa"=>"沖縄県",

"overseas"=>"海外",
"otherOnlineShops"=>"その他オンラインショップ",

/*"dealers"=>array(
	"hokkaidoTohoku"=>array(
		array(
			"name"=>"丸井今井札幌本店",
			"prefecture"=>"北海道",
			"address"=>"札幌市中央区南1条西2丁目",
			"floor"=>"一条館 4F 紳士服",
			"tel"=>"011-205-1151",
			"map"=>"%E4%B8%B8%E4%BA%95%E4%BB%8A%E4%BA%95+%E6%9C%AD%E5%B9%8C%E6%9C%AC%E5%BA%97+%E4%B8%80%E6%9D%A1%E9%A4%A8/@43.0596655,141.352902,17z/data=!3m2!4b1!5s0x5f0b2982d67f29ab:0xcaa3eba46cc03b80!4m5!3m4!1s0x5f0b2982d680442f:0x8f6af94cfd95bc28!8m2!3d43.0596655!4d141.3550907",
		),
	),
),*/

);

?>