<?php

// トップページに表示する特集のバナー
$topFeatureDates = array(
	"2023-07-21",
	"shirt2025",
	"leather2024",
);

// 特集リスト
$features = array(
	array(
		"date" => "shirt2025",
		"title-en" => "スリムなシャツハンガー",
		"title-ja" => "クローゼットに開放感を",
		"image" => "feature-shirt2025-banner.webp",
	),
	array(
		"date" => "2025-2708",
		"title-en" => "記念日特集",
		"title-ja" => "2/7～9は木製ハンガーにとって大事な3日間",
		"image" => "feature-2025-2708-banner.webp",
	),
	array(
		"date" => "leathersday2024",
		"title-en" => "Leathers Day2024",
		"title-ja" => "レザー好きが集まるイベントに出展",
		"image" => "feature-leathersday2024-banner.webp",
	),
	array(
		"date" => "leather2024",
		"title-en" => "Leather Jacket Hangers",
		"title-ja" => "レザーにおすすめのハンガーをご紹介",
		"image" => "feature-leather2024-banner.webp",
	),
	array(
		"date" => "father-gallery2024",
		"title-en" => "Father's Day Illustration Gallery",
		"title-ja" => "父の日イラストギャラリー",
		"image" => "feature-father-gallery2024-banner.jpg",
	),
	array(
		"date" => "summer",
		"title-en" => "SHIRT HANGERS",
		"title-ja" => "シンプルな収納 心地よい夏",
		"image" => "feature-summer2024-banner.jpg",
	),
	array(
		"date" => "trunkshow2024ny",
		"title-en" => "Trunk Show In New York",
		"title-ja" => "NYでトランクショー開催",
		"image" => "feature-trunkshow2024ny-banner.jpg",
	),
	array(
		"date" => "2024-02-08",
		"title-en" => "木製ハンガーの日 2024",
		"title-ja" => "2月8日は木製ハンガーの日",
		"image" => "feature-0208-banner.jpg",
	),
	array(
		"date" => "2024-02-07",
		"title-en" => "国産ブナ材の日 2024",
		"title-ja" => "2月7日は国産ブナ材の日",
		"image" => "feature-0207-banner.jpg",
	),

	array(
		"date" => "suits-mainte",
		"title-en" => "スーツメンテナンス特集",
		"title-ja" => "適切なお手入れと保管方法をご紹介",
		"image" => "feature-suits-mainte-banner.jpg",
	),
	array(
		"date" => "spring2024",
		"title-en" => "Spring Gift",
		"title-ja" => "始まりの季節におすすめのギフト",
		"image" => "feature-spring2024-banner.jpg",
	),
	array(
		"date" => "leathersday2023",
		"title-en" => "Leathers Day2023",
		"title-ja" => "レザー好きが集まるイベントに出展",
		"image" => "feature-leathersday2023-banner.jpg",
	),
	array(
		"date" => "trunkshow2023hk",
		"title-en" => "Trunk Show In Hong Kong",
		"title-ja" => "香港でトランクショー開催",
		"image" => "feature-trunkshow2023hk-banner.jpg",
	),
	array(
		"date" => "2023-07-21",
		"title-en" => "NATURAL COLOR series",
		"title-ja" => "NAKATA HANGER のナチュラルカラー",
		"image" => "feature-20230721-banner.jpg",
	),

	array(
		"date" => "2023-06-13",
		"title-en" => "SHIRT HANGERS",
		"title-ja" => "収納性に優れたシャツハンガー特集",
		"image" => "feature-20230613-banner.jpg",
	),
	array(
		"date" => "2023-07-06",
		"title-en" => "Father's Day Illustration Gallery",
		"title-ja" => "父の日イラストギャラリー",
		"image" => "feature-20230706-banner.jpg",
	),
	// array(
	// 	"date"=>"2023-05-19",
	// 	"title-en"=>"Father’s Day 2023",
	// 	"title-ja"=>"手描きイラストハンガー&限定ラッピング",
	// 	"image"=>"feature-20230519-banner.jpg",
	// ),
	array(
		"date" => "2023-04-20",
		"title-en" => "RGD-06",
		"title-ja" => "木ならではの味わい深さが魅力の1本",
		"image" => "feature-20230420-banner.jpg",
	),
	array(
		"date" => "nakata_artdisplay",
		"title-en" => "NAKATA Art Display",
		"title-ja" => "in London by Arterton",
		"image" => "feature-artdisplay-banner.jpg",
	),
	// array(
	// 	"date"=>"2023-01-18",
	// 	"title-en"=>"Spring Gift",
	// 	"title-ja"=>"昇進祝いや入社祝い、栄転ギフト",
	// 	"image"=>"feature-20230118-banner.jpg",
	// ),
	// array(
	// 	"date"=>"2022-11-24",
	// 	"title-en"=>"Holiday Gift",
	// 	"title-ja"=>"心温まるホリデーギフト",
	// 	"image"=>"feature-20221124-banner.jpg",
	// ),
	// array(
	// 	"date"=>"2022-09-01",
	// 	"title-en"=>"Respect for the Aged Day",
	// 	"title-ja"=>"手描きイラスト入り敬老の日ギフト",
	// 	"image"=>"feature-20190808-banner.jpg",
	// ),
	array(
		"date" => "2022-08-25",
		"title-en" => "NAKATA HANGER<br>15th Anniversary",
		"title-ja" => "15周年を迎えて",
		"image" => "feature-20220825-banner.jpg",
	),
	// array(
	// 	"date"=>"2022-06-27",
	// 	"title-en"=>"スリムなシャツハンガー",
	// 	"title-ja"=>"収納性に優れた厚み15mm",
	// 	"image"=>"feature-20220627-banner.jpg",
	// ),
	// array(
	// 	"date"=>"2022-07-11",
	// 	"title-en"=>"Father's Day Illustration Gallery",
	// 	"title-ja"=>"父の日イラストギャラリー2022",
	// 	"image"=>"feature-20220511-banner.jpg",
	// ),
	// array(
	// 	"date"=>"2022-05-11",
	// 	"title-en"=>"Father’s Day 2022",
	// 	"title-ja"=>"頑張るお父さんへの父の日ギフト",
	// 	"image"=>"feature-20220511-banner.jpg",
	// ),
	// array(
	// 	"date"=>"2022-04-08",
	// 	"title-en"=>"Happy Mother's Day",
	// 	"title-ja"=>"「いつもありがとう」を伝えるきっかけに",
	// 	"image"=>"feature-20220408-banner.jpg",
	// 	"url"=>getPageUrl(2345393),
	// ),
	array(
		"date" => "2022-03-15",
		"title-en" => "世界一のハンガーを届ける。",
		"title-ja" => "組立編",
		"image" => "feature-20220315-01-top.jpg",
	),
	// array(
	// 	"date"=>"2022-03-01",
	// 	"title-en"=>"HELLO NEW LIFE 2022",
	// 	"title-ja"=>"”新生活ハンガーセットではじめる春支度",
	// 	"image"=>"feature-20220301-01-top.jpg",
	// ),
	array(
		"date" => "2022-02-08-fuji",
		"title-en" => "重なり合う<br>「流線」と「色彩」",
		"title-ja" => "”富士山”をモチーフにハンガーを作りました。",
		"image" => "feature-20220208fuji-01-top.jpg",
	),
	// array(
	// 	"date"=>"2022-02-07",
	// 	"title-en"=>"『国産ブナ材の日』",
	// 	"title-ja"=>"毎年2月7日を『国産ブナ材の日』に制定しました。",
	// 	"image"=>"feature-20220207-01-top.jpg",
	// ),
	// array(
	// 	"date"=>"2022-02-08",
	// 	"title-en"=>"『木製ハンガーの日』",
	// 	"title-ja"=>"毎年2月8日を「木製ハンガーの日」に制定しました。",
	// 	"image"=>"feature-20220208-01-top.jpg",
	// ),
	// array(
	// 	"date"=>"2022-02-14",
	// 	"title-en"=>"Valentine's Gift 2022",
	// 	"title-ja"=>"バレンタインは大切な人にハンガーを贈りませんか。",
	// 	"image"=>"feature-20220214-01-top.jpg",
	// ),
	// array(
	// 	"date"=>"2021-11-25",
	// 	"title-en"=>"心躍る季節ならではの彩りを",
	// 	"title-ja"=>"Christmas gift 2021",
	// 	"image"=>"feature-20211125-01-top.jpg",
	// ),
	// array(
	// 	"date"=>"2021-11-12",
	// 	"title-en"=>"“ふく”をかける贈りもの",
	// 	"title-ja"=>"大切なあの人へのギフトに。",
	// 	"image"=>"feature-20211110-01-top.jpg",
	// ),
	array(
		"date" => "2021-10-27",
		"title-en" => "世界一のハンガーを彩る。",
		"title-ja" => "塗装編",
		"image" => "feature-20211027-01-top.jpg",
	),
	// array(
	// 	"date"=>"2021-07-06",
	// 	"title-en"=>"SHIRT HANGERS",
	// 	"title-ja"=>"スリム（厚み15mm）なシャツハンガー",
	// 	"image"=>"feature-20210825-01-top.jpg",
	// ),
	//array(
	//	"date"=>"2021-08-12",
	//	"title-en"=>"Happy Box",
	//	"title-ja"=>"数量期間限定　30％OFF",
	//	"image"=>"feature-20210812-01-top.jpg",
	//),
	// array(
	// 	"date"=>"2021-07-20",
	// 	"title-en"=>"14th ANNIVERSARY",
	// 	"title-ja"=>"NAKATA HANGER 14周年を迎えて",
	// 	"image"=>"feature-20210720-01-top.jpg",
	// ),
	// array(
	// 	"date"=>"2021-07-30",
	// 	"title-en"=>"Father's Day Illustration Gallery",
	// 	"title-ja"=>"父の日イラストギャラリー2021",
	// 	"image"=>"feature-20210730-1.jpg",
	//"top-banner-link"=>"top_banner_fathersday2020",
	//"ended"=>true,
	// ),
	// array(
	// 	"date"=>"2021-05-11",
	// 	"title-en"=>"Father’s Day 2021",
	// 	"title-ja"=>"手描きイラスト入りの父の日ギフト",
	// 	"image"=>"feature-20210511-01-top.jpg",
	// ),

	// array(
	// 	"date"=>"2021-04-12",
	// 	"title-en"=>"新生活特集",
	// 	"title-ja"=>"新しいライフスタイルをはじめてみませんか？",
	// 	"image"=>"feature-20210412-01-top.jpg",
	// ),

	// array(
	// 	"date"=>"2021-03-31",
	// 	"title-en"=>"母の日ギフト",
	// 	"title-ja"=>"お母さんに、感謝の気持ちとふくかけの願いを込めて",
	// 	"image"=>"feature-20210331-01-top.jpg",
	// ),

	array(
		"date" => "2021-03-19",
		"title-en" => "世界一のハンガーを作る。",
		"title-ja" => "成型編",
		"image" => "feature-20210319-01.jpg",
	),
	// array(
	// 	"date"=>"2021-02-15",
	// 	"title-en"=>"サンプル貸出",
	// 	"title-ja"=>"ハンガー貸し出しサービス",
	// 	"image"=>"sample-top.png",
	// 	"top-banner-link"=>"top_banner_sample",
	// 	"url"=>getHref("sample"),
	// ),

	// array(
	// 	"date"=>"2021-01-20",
	// 	"title-en"=>"Valentine 2021",
	// 	"title-ja"=>"チョコレートのようなハンガー",
	// 	"image"=>"feature-20190115-1.jpg",
	// 	"banner-image-style-pc"=>"background-size:152%;",
	// 	"banner-image-style-sp"=>"background-size:112%;",
	// 	"top-banner-link"=>"top_banner_valentine2021",
	// 	"url"=>getPageUrl(2519612),
	// ),

	// array(
	// 	"date"=>"2021-02-08",
	// 	"title-en"=>"『木製ハンガーの日』",
	// 	"title-ja"=>"2月8日は『木製ハンガーの日』",
	// 	"image"=>"hday-banner-01.jpg",
	// 	//"top-banner-link"=>"hday-banner-01",
	// ),

	array(
		"date" => "2021-01-08",
		"title-en" => "歌舞伎座ハンガー",
		"title-ja" => "数々の名舞台が演じられた大舞台の檜を使用<div style='right:21px; bottom:0px; font-size:1.2rem; position:absolute;'>&copy 松竹株式会社</div>",
		"image" => "kabuki-banner-01.jpg",
		"top-banner-link" => "top_banner_kabuki2021",
	),

	// array(
	// 	"date"=>"2020-12-01",
	// 	"title-en"=>"Christmas Gift 2020",
	// 	"title-ja"=>"心躍る季節ならではの彩りを",
	// 	"image"=>"feature-20201201-1.jpg",
	// 	"ended"=>true,
	// ),

	// array(
	// 	"date"=>"2020-08-04",
	// 	"title-en"=>"Father's Day Illustration Gallery",
	// 	"title-ja"=>"父の日イラストギャラリー2020",
	// 	"image"=>"feature-20200804-1.jpg",
	// ),

	//	array(
	//		"date"=>"2020-06-15",
	//		"title-en"=>"サンプルハンガー貸出し",
	//		"title-ja"=>"キャンペーン期間：6月17日（水）～7月17日（金）",
	//		"image"=>"feature-20200615-1.jpg",
	//		//"top-banner-link"=>"top_banner_fathersday2020",
	//		"ended"=>true,
	//	),

	// array(
	// 	"date"=>"2020-04-30",
	// 	"title-en"=>"Father’s Day 2020",
	// 	"title-ja"=>"手書きイラスト入りの父の日ギフト",
	// 	"image"=>"feature-20200430-1.jpg",
	// 	"top-banner-link"=>"top_banner_fathersday2020",
	// ),
	array(
		"date" => "2020-04-04",
		"title-en" => "Men's Hanger Set",
		"title-ja" => "セットで揃えるメンズハンガー",
		"image" => "feature-20200404-1.jpg",
		"top-banner-link" => "top_banner_menshangerset",
	),
	// array(
	// 	"date"=>"2020-03-31",
	// 	"title-en"=>"Mother’s Day",
	// 	"title-ja"=>"大切なお母さんへ　ふくをかけるプレゼント",
	// 	"image"=>"feature-20200331-1.jpg",
	// 	"top-banner-link"=>"top_banner_mothersday2020",
	// 	"ended"=>true,
	// ),
	// array(
	// 	"date"=>"2020-01-27",
	// 	"title-en"=>"SPECIAL SMOKED BROWN HANGER",
	// 	"title-ja"=>"スモークブラウンで揃えるこだわりのクローゼット。どんなお部屋でも使いやすいスモークブラウンで統一しませんか？",
	// 	"image"=>"feature-20200127-1.jpg",
	// 	"banner-image-style-pc"=>"background-position:0 top;",
	// 	"banner-image-style-sp"=>"background-position:0 top;",
	// 	"ended"=>true,
	// ),
	// array(
	// 	"date"=>"2020-01-18",
	// 	"title-en"=>"The Chocolate Hanger for Valentine",
	// 	"title-ja"=>"大切な人に想いを込めて。チョコレートを思わせる華やかなハンガーはいかが？",
	// 	"image"=>"feature-20200118-1.jpg",
	// 	"ended"=>true,
	// ),
	// array(
	// 	"date"=>"2019-11-26",
	// 	"title-en"=>"Christmas Gift 2019",
	// 	"title-ja"=>"心躍る季節ならではの彩りを",
	// 	"image"=>"feature-20191126-1.jpg",
	// 	"banner-image-style-pc"=>"background-position:0 60%; background-size:163%;",
	// 	"banner-image-style-sp"=>"background-position:0 59%; background-size:163%;",
	// 	"ended"=>true,
	// ),
	// array(
	// 	"date"=>"2019-08-08",
	// 	"title-en"=>"Respect for the Elderly",
	// 	"title-ja"=>"世界でひとつの敬老の日ギフト",
	// 	"image"=>"feature-20190808-banner.jpg",
	// 	"ended"=>true,
	// ),
	// array(
	// 	"date"=>"2019-06-12",
	// 	"title-en"=>"Shirt Hangers",
	// 	"title-ja"=>"シャツハンガー +1本 プレゼント",
	// 	"image"=>"feature-20190612-01.jpg",
	// 	"ended"=>true,
	// ),
	array(
		"date" => "2019-04-23",
		"title-en" => "Women's Hanger Life",
		"title-ja" => "ワードローブを美しく保つハンガー",
		"image" => "feature-20190423-01.jpg",
	),
	// 	array(
	// 		"date"=>"2019-04-22",
	// 		"title-en"=>"Father's Day 2019",
	// 		"title-ja"=>"世界でひとつの父の日ギフト",
	// 		"image"=>"feature-20190422.jpg",
	// 	),
	// 	array(
	// 		"date"=>"2019-02-21",
	// 		"title-en"=>"Let's start something new.",
	// 		"title-ja"=>"新しい季節のはじまり",
	// 		"image"=>"feature-20190221-1.jpg",
	// //		"title-en-style"=>"font-size:3.3rem;",
	// 		"banner-image-style-pc"=>"background-position-y:23%;",
	// 	),
	// 	array(
	// 		"date"=>"2019-01-15",
	// 		"title-en"=>"The Chocolate Hanger",
	// 		"title-ja"=>"チョコレートのように艶やかなハンガー",
	// 		"image"=>"feature-20190115-1.jpg",
	// 		"banner-image-style-pc"=>"background-position:4% 56%; background-size:176%;",
	// 		"banner-image-style-sp"=>"background-position:24% 55%; background-size:140%;",
	// 		"ended"=>true,
	// 	),
	// 	array(
	// 		"date"=>"2018-11-26",
	// 		"title-en"=>"Winter Gift",
	// 		"title-ja"=>"冬の贈りもの",
	// 		"image"=>"feature-20181126-1.jpg",
	// 		"banner-image-style-pc"=>"background-position:0 top;",
	// 		"banner-image-style-sp"=>"background-position:0 23%;",
	// 	),
	// 	array(
	// 		"date"=>"2018-11-25",
	// 		"title-en"=>"Christmas Gift 2018",
	// 		"title-ja"=>"心躍る季節ならではの彩りを",
	// 		"image"=>"feature-20181125-1.jpg",
	// 		"banner-image-style-pc"=>"background-position:78% 68%; background-size:185%;",
	// 		"banner-image-style-sp"=>"background-position:75% 64%; background-size:185%;",
	// 		"ended"=>true,
	// 	),
	array(
		"date" => "2018-10-29",
		"title-en" => "Outerwear Hangers",
		"title-ja" => "アウター用ハンガー",
		"image" => "feature-20181029-1.jpg",
		"banner-image-style-pc" => "background-position:78% 29%;",
		"banner-image-style-sp" => "background-position:78% 0;",
	),
);
